[package]
name = "odbc-iter"
version = "0.1.0"
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
edition = "2018"

[features]
# no features by default
default = []
test-hive = []
test-sql-server = []
test-monetdb = []

[dependencies]
odbc-sys = "0.6.1"
odbc = "0.9.15"
serde_json = "1.0.33"
regex = "1.1.0"
lazy_static = "1.2.0"
log = "0.4.6"
error-context = { git = "https://github.com/jpastuszek/error-context" }
### for odbc-query
cotton = { git = "https://github.com/jpastuszek/cotton.git" }
structopt = "0.2.14"

[dev-dependencies]
assert_matches = "1.3.0"
