[package]
name = "odbc-iter"
version = "0.1.0"
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
edition = "2018"

[features]
# no features by default
default = []
test-hive = []
test-sql-server = []

[dependencies]
#odbc = "0.9.6"
#odbc = { path = "../odbc-rs" }
odbc = { git = "https://github.com/jpastuszek/odbc-rs.git" }
serde_json = "1.0.33"
odbc-sys = "0.6.1"
log = "0.4.6"
regex = "1.1.0"
problem = "0.1.0"
lazy_static = "1.2.0"
# odbc-query
cotton = { git = "https://github.com/jpastuszek/cotton.git" }
structopt = "0.2.12"

[dev-dependencies]
assert_matches = "1.3.0"
